### ISSUE TITLE
Delegated Form Create Error - Conditional Visibility Issues

### ISSUE THREAD

**Issue by T4E-JAnderson** [Tools4everBV/HelloID-Conn-SA-Source-HelloID-DelegatedForms#2] opened 2021-01-20 21:47 UTC
Received an error at end of script due to a missing GUID.  Not sure if it was caused by an earlier error adding Access Groups (one of which did not exist at the target.)

2 Questions:
1)  Should Access Groups be part of this export, or should they be removed from the Delegated Form before it is exported by this script?
2)  Why did it lose track of the DynamicFormGuid?

[createform.txt](https://github.com/Tools4everBV/HelloID-Conn-SA-Source-HelloID-DelegatedForms/files/5845478/createform.txt)

**Comment by T4E-JAnderson** [comment] 2021-01-20 22:06
Looks like the missing group wasn't an issue upon more digging.

Tracked issue back to the creation of the Form, an unhandled error:
Dynamic form 'DPWR Config Form', message: Unrecognized escape sequence. (1335): 

Upon further digging in the provided raw JSON, it looks like the Conditional Visibility rules were not encoded correctly, but this is only a guess.
![image](https://user-images.githubusercontent.com/75453090/105247019-f7d9d600-5b28-11eb-8476-6fb2c8008783.png)

**Comment by T4E-JAnderson** [comment] 2021-01-20 22:38
Confirmed, definitely some excessive escapes in the generated Form extract.
I removed the extra escapes, and that fixed both the JSON Formater shown above, but also allowed the script to create the requested form and finish without further error.

Example of updated hideExpression:
```text
"hideExpression":"model[\"radioaction\"]!==\u0027Add\u0027",
```
Original:
```text
"hideExpression":"model\[\\"radioaction\\"]!==\u0027Add\u0027",
```
This also now more closely matches the raw 'Editor' view of the form in HelloID:
![image](https://user-images.githubusercontent.com/75453090/105249575-2f4a8180-5b2d-11eb-8a1c-d5c46a823448.png)

**Comment by T4E-JAnderson** [comment] 2021-01-20 22:49
Quick note on Groups and Categories:
I see these are both predefined in the Extract script.  Can these be included in the original export as well, or do they need to be manually set in the generated CreateForm.ps1 (or the appropriate spot in the Extract script)?

**Comment by Michiel85** [comment] 2021-01-21 12:18
1. There are some issues with the Dynamic JSON export and importing it again. Have tried to fix it, but probably not in all cases. Will have a further look into this.
2. At this moment it is by design that the Delegated Form categories are not exported with this script, but entered manually. But will add this in the near future.
3. At this moment it is by design that the Delegated Form groups are not exported with this script, but entered manually. I will check the API support for this and then add it in the future

**Comment by Michiel85** [comment] 2021-02-05 15:39
1. The issue with escaping brackets has been fixed for all possible (known) situations
2. The delegated form categories now can be exported of hardcoded (configurable in script)
3. Groups will be hardcoded for now. Because you can not be sure the Group Names do exist in the new HelloID environment (you can check), but also don't know what other accounts or rights have been assigned to the groups.

**Closed as completed by Michiel85** 2021-02-05 15:39 UTC
